#include <iostream>
#include <algorithm>
#include <iomanip>
#include <random>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtc/quaternion.hpp>

#include "../renderer/render.h"
#include "../renderer/camera.h"
#include "../renderer/cube.h"
#include "../physics/rigidbody.h"
#include "../physics/physicssolver.h"

using namespace std;

Camera* activeCamera = nullptr;
bool isDragging = false;
double lastMouseX = 0.0;
double lastMouseY = 0.0;

void framebufferSizeChanged(GLFWwindow* window, int width, int height) {
    glViewport(0, 0, width, height);
}

void mouseButtonCallback(GLFWwindow* window, int button, int action, int mods) {
    if (button != GLFW_MOUSE_BUTTON_LEFT) return;
    if (action == GLFW_PRESS) {
        isDragging = true;
        glfwGetCursorPos(window, &lastMouseX, &lastMouseY);
    } else if (action == GLFW_RELEASE) {
        isDragging = false;
    }
}

void cursorPosCallback(GLFWwindow* window, double xPos, double yPos) {
    if (!isDragging || activeCamera == nullptr) return;
    const float deltaX = static_cast<float>(xPos - lastMouseX);
    const float deltaY = static_cast<float>(yPos - lastMouseY);
    lastMouseX = xPos;
    lastMouseY = yPos;
    activeCamera->processMouseDrag(deltaX, -deltaY);
}

void scrollCallback(GLFWwindow* window, double xOffset, double yOffset) {
    if (activeCamera == nullptr) return;
    activeCamera->processScroll(static_cast<float>(yOffset));
}

// ===========================================================================
// Mass property helper (Day 14 Part 3)
// ===========================================================================
void setCubeMassProperties(RigidBody& body, float mass) {
    // Computes both linear AND angular mass properties from a single mass
    // value, assuming a uniform solid cube (this engine's only shape so
    // far) of the body's own side length. Centralizing this in one place
    // avoids hand-computing inertia separately at every spawn site and
    // risking an inconsistent mass/inertia pair -- the same risk that
    // mass/inverseMass already carried before this helper existed.
    const float side = body.scale.x;
    // Assumes a uniform (cube-shaped) scale, which is all this engine spawns.
 
    body.mass = mass;
    body.inverseMass = (mass > 0.0f) ? (1.0f / mass) : 0.0f;
 
    // Standard solid-cube moment of inertia about any axis through its
    // center: I = (1/6) * m * s^2. Heavier or larger cubes resist spinning
    // more, exactly mirroring how heavier objects resist accelerating.
    body.updateInertiaTensor();
}
 
// ===========================================================================
// Test scenarios (all generated by Claude)
// ===========================================================================
// Each function returns a self-contained scene, and every scenario is
// centered near the world origin (x and z close to 0) so the same static
// camera frames whichever one is active -- no per-test camera tuning needed.
//
// To demonstrate one at a time: in main(), uncomment exactly ONE of the
// `bodies = spawnXxx();` lines below and leave the rest commented out.
// Uncommenting more than one at once will not compile (both would try to
// initialize the same 'bodies' variable) -- that's intentional, it forces
// exactly one active scenario at a time.
//
// Day 13 friction tests:
//   spawnTestSlidingCube()        - Test 1: cube-floor friction alone
//   spawnTestCubeOnCube()         - Test 2: cube-cube friction, both affected
//   spawnTestCubeStack()          - Test 3a: stack stability at rest
//   spawnTestPushStack()          - Test 3b: stack stability when pushed
//   spawnTestFrictionComparison() - Test 4: low vs. high friction side by side
//
// Day 14 rotation tests:
//   spawnTestDropFlat()           - Test 1: drop flat -> minimal rotation
//   spawnTestDropTilted()         - Test 2: drop tilted -> tips and settles
//   spawnTestHitCenter()          - Test 3: center hit -> mostly translation
//   spawnTestHitCorner()          - Test 4: off-center hit -> translation + spin
// ===========================================================================
 
std::vector<RigidBody> spawnTestHeadOn() {
    // Test A: head-on collision, pure X-axis, equal masses.
    // Two cubes on a direct collision course, dropped from the same height
    // so gravity is identical for both -- isolates the horizontal response.
    std::vector<RigidBody> bodies;
 
    RigidBody left;
    left.position = glm::vec3(-2.5f, 4.0f, 0.0f);
    left.velocity = glm::vec3(3.0f, 0.0f, 0.0f);
    setCubeMassProperties(left, 1.0f);
    left.restitution = 0.5f;
    bodies.push_back(left);
 
    RigidBody right;
    right.position = glm::vec3(2.5f, 4.0f, 0.0f);
    right.velocity = glm::vec3(-3.0f, 0.0f, 0.0f);
    setCubeMassProperties(right, 1.0f);
    right.restitution = 0.5f;
    bodies.push_back(right);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestVertical() {
    // Test B: vertical collision, body-body (not the floor).
    // One cube rests near the floor; a second drops straight down onto it.
    std::vector<RigidBody> bodies;
 
    RigidBody bottom;
    bottom.position = glm::vec3(0.0f, 0.5f, 0.0f);
    bottom.velocity = glm::vec3(0.0f);
    setCubeMassProperties(bottom, 1.0f);
    bottom.restitution = 0.3f;
    bodies.push_back(bottom);
 
    RigidBody dropper;
    dropper.position = glm::vec3(0.0f, 6.0f, 0.0f);
    dropper.velocity = glm::vec3(0.0f, -4.0f, 0.0f);
    setCubeMassProperties(dropper, 1.0f);
    dropper.restitution = 0.3f;
    bodies.push_back(dropper);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestDiagonal() {
    // Test C: diagonal collision, X, Y, and Z velocity components at once.
    // Note the AABB collision normal is still always axis-aligned (SAT picks
    // whichever single axis has the smallest overlap) -- that's correct
    // behaviour for box-vs-box collision -- but the *approach* here is
    // genuinely diagonal, which exercises the general impulse formula well.
    std::vector<RigidBody> bodies;
 
    RigidBody diagA;
    diagA.position = glm::vec3(-2.0f, 5.0f, -2.0f);
    diagA.velocity = glm::vec3(2.0f, -1.0f, 2.0f);
    setCubeMassProperties(diagA, 1.0f);
    diagA.restitution = 0.5f;
    bodies.push_back(diagA);
 
    RigidBody diagB;
    diagB.position = glm::vec3(2.0f, 4.0f, 2.0f);
    diagB.velocity = glm::vec3(-2.0f, 0.5f, -2.0f);
    setCubeMassProperties(diagB, 1.0f);
    diagB.restitution = 0.5f;
    bodies.push_back(diagB);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestDifferentMasses() {
    // Test D: momentum transfer between different masses.
    // A heavy cube (mass 8) barrels into a light, stationary cube (mass 0.5).
    // Because the impulse each body receives is scaled by its own
    // inverseMass, the light cube should fly off much faster than the
    // heavy cube slows down. Their rotational inertia now also differs
    // proportionally (Day 14) -- the heavy cube resists spinning more too.
    std::vector<RigidBody> bodies;
 
    RigidBody heavy;
    heavy.position = glm::vec3(-2.5f, 3.0f, 0.0f);
    heavy.velocity = glm::vec3(3.0f, 0.0f, 0.0f);
    setCubeMassProperties(heavy, 8.0f);
    heavy.restitution = 0.4f;
    bodies.push_back(heavy);
 
    RigidBody light;
    light.position = glm::vec3(1.5f, 3.0f, 0.0f);
    light.velocity = glm::vec3(0.0f);
    setCubeMassProperties(light, 0.5f);
    light.restitution = 0.4f;
    bodies.push_back(light);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestSlidingCube() {
    // Day 13 Test 1: Sliding cube.
    // A single cube is given horizontal velocity right at floor height (no
    // fall, no bounce -- isolates friction's deceleration effect). Expected:
    // the cube slides, gradually slows, and eventually comes to a full stop.
    std::vector<RigidBody> bodies;
 
    RigidBody cube;
    cube.position = glm::vec3(-3.5f, 0.5f, 0.0f);
    cube.velocity = glm::vec3(4.0f, 0.0f, 0.0f);
    setCubeMassProperties(cube, 1.0f);
    cube.restitution = 0.1f;
    // Low restitution so it doesn't hop on the small initial floor contact.
    cube.friction    = 0.4f;
    // Moderate friction -- should visibly decelerate over roughly a second.
    bodies.push_back(cube);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestCubeOnCube() {
    // Day 13 Test 2: Cube on cube.
    // Cube A slides along the floor and hits stationary Cube B. Expected:
    // friction affects their relative motion both while sliding beforehand
    // (floor friction slows A down before impact) and at the contact
    // between A and B (the two share momentum, then both decelerate from
    // floor friction afterward). Both cubes are visibly affected.
    std::vector<RigidBody> bodies;
 
    RigidBody a;
    a.position = glm::vec3(-3.5f, 0.5f, 0.0f);
    a.velocity = glm::vec3(4.0f, 0.0f, 0.0f);
    setCubeMassProperties(a, 1.0f);
    a.restitution = 0.2f;
    a.friction    = 0.4f;
    bodies.push_back(a);
 
    RigidBody b;
    b.position = glm::vec3(0.0f, 0.5f, 0.0f);
    b.velocity = glm::vec3(0.0f);
    setCubeMassProperties(b, 1.0f);
    b.restitution = 0.2f;
    b.friction    = 0.4f;
    bodies.push_back(b);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestCubeStack() {
    // Day 13 Test 3 (part 1): Cube stack stability.
    // Four cubes stacked exactly on top of each other and dropped a short
    // distance onto the floor. Expected: the stack remains standing with
    // minimal jitter once SOLVER_ITERATIONS propagates the contact forces
    // all the way down to the floor.
    std::vector<RigidBody> bodies;
 
    for (int i = 0; i < 4; ++i) {
        RigidBody cube;
        cube.position = glm::vec3(0.0f, 0.55f + static_cast<float>(i) * 1.02f, 0.0f);
        // Tiny 0.02 gap between cubes so they start just barely separated
        // (avoids beginning the simulation already overlapping, which would
        // otherwise trigger one large correction on the very first step).
        cube.velocity = glm::vec3(0.0f);
        setCubeMassProperties(cube, 1.0f);
        cube.restitution = 0.1f;
        // Low restitution -- stacked cubes shouldn't bounce off each other.
        cube.friction    = 0.6f;
        // Higher friction helps the stack resist toppling sideways.
        bodies.push_back(cube);
    }
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestPushStack() {
    // Day 13 Test 3 (part 2): Push the bottom cube of a stack.
    // Same 4-cube stack as spawnTestCubeStack(), but the bottom cube starts
    // with horizontal velocity, as if it had just been shoved. Expected:
    // friction between the cubes should make the stack resist sliding
    // coherently -- the bottom cube shouldn't shoot out from under the
    // others; the whole stack should drag together and settle, rather than
    // the top cubes staying behind while the bottom one escapes. With
    // Day 14 rotation, you may also see the stack lean/wobble as friction
    // torque acts on each cube, not just pure sliding.
    std::vector<RigidBody> bodies;
 
    for (int i = 0; i < 4; ++i) {
        RigidBody cube;
        cube.position = glm::vec3(0.0f, 0.55f + static_cast<float>(i) * 1.02f, 0.0f);
        cube.velocity = (i == 0) ? glm::vec3(3.0f, 0.0f, 0.0f) : glm::vec3(0.0f);
        // Only the bottom cube (i == 0) gets the initial push.
        setCubeMassProperties(cube, 1.0f);
        cube.restitution = 0.1f;
        cube.friction    = 0.6f;
        bodies.push_back(cube);
    }
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestFallingCubes() {
    // Day 13 Test 3: Falling cubes.
    // Several cubes spawn above the floor in a loose scattered cluster (not
    // perfectly aligned, so they don't all land in a single neat column) and
    // fall together. Expected: they collide with each other and the floor,
    // then settle into a stable pile without exploding apart.
    std::vector<RigidBody> bodies;
 
    const glm::vec3 offsets[] = {
        { -1.0f, 3.0f,  0.6f}, { 0.8f, 3.6f, -0.5f}, {-0.4f, 4.4f,  0.9f},
        {  1.1f, 5.0f,  0.2f}, {-1.2f, 5.6f, -0.8f}, { 0.3f, 6.4f,  0.5f},
    };
 
    for (const auto& offset : offsets) {
        RigidBody cube;
        cube.position = offset;
        cube.velocity = glm::vec3(0.0f);
        setCubeMassProperties(cube, 1.0f);
        cube.restitution = 0.2f;
        cube.friction    = 0.5f;
        bodies.push_back(cube);
    }
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestFrictionComparison() {
    // Day 13 Test 4: Different friction values, side by side.
    // Two identical cubes given the same starting horizontal velocity, but
    // one has very low friction and the other very high friction. They're
    // offset in Z so they don't collide with each other -- both are visible
    // in the same shot. Expected: the low-friction cube slides much farther
    // than the high-friction cube, which stops almost immediately.
    std::vector<RigidBody> bodies;
 
    RigidBody lowFriction;
    lowFriction.position = glm::vec3(-3.0f, 0.5f, -1.5f);
    lowFriction.velocity = glm::vec3(4.0f, 0.0f, 0.0f);
    setCubeMassProperties(lowFriction, 1.0f);
    lowFriction.restitution = 0.1f;
    lowFriction.friction    = 0.03f;
    // Nearly frictionless -- should slide most of the way across the scene.
    bodies.push_back(lowFriction);
 
    RigidBody highFriction;
    highFriction.position = glm::vec3(-3.0f, 0.5f, 1.5f);
    highFriction.velocity = glm::vec3(4.0f, 0.0f, 0.0f);
    setCubeMassProperties(highFriction, 1.0f);
    highFriction.restitution = 0.1f;
    highFriction.friction    = 1.2f;
    // High friction -- should stop within a fraction of a second.
    bodies.push_back(highFriction);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestDropFlat() {
    // Day 14 Test 1: Drop a cube flat.
    // A single cube falls straight down with identity orientation and zero
    // angular velocity. Expected: minimal rotation. The floor's contact
    // point lands directly below the body's center (r purely vertical,
    // parallel to the normal), so the normal impulse alone produces zero
    // torque -- and with no horizontal velocity, there's no friction
    // torque either. The cube should land and stay level.
    std::vector<RigidBody> bodies;
 
    RigidBody cube;
    cube.position        = glm::vec3(0.0f, 4.0f, 0.0f);
    cube.velocity        = glm::vec3(0.0f);
    cube.orientation     = glm::quat(1.0f, 0.0f, 0.0f, 0.0f);
    // Identity quaternion -- perfectly level, no initial tilt.
    cube.angularVelocity = glm::vec3(0.0f);
    setCubeMassProperties(cube, 1.0f);
    cube.restitution = 0.3f;
    cube.friction    = 0.5f;
    bodies.push_back(cube);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestDropTilted() {
    // Day 14 Test 2: Drop a cube slightly tilted.
    // Starts rotated ~20 degrees around Z, with a small initial angular
    // velocity in the same direction, representing the nudge that put it
    // off-balance before release. Expected: it tips and settles.
    //
    // Caveat: collision detection here still uses an axis-aligned AABB
    // (see AABB::fromRigidBody's comment), not the cube's true rotated
    // shape, so the floor contact doesn't know a corner touches down first
    // the way a real tilted box would. What you'll actually observe is the
    // initial spin gradually damping out through the floor's normal +
    // friction impulses (the same resting-contact mechanism that damps
    // linear jitter) until angularVelocity settles near zero -- a
    // reasonable stand-in for "tips and settles" until a future OBB
    // collision pass makes corner-first contact physically exact.
    std::vector<RigidBody> bodies;
 
    RigidBody cube;
    cube.position        = glm::vec3(0.0f, 4.0f, 0.0f);
    cube.velocity        = glm::vec3(0.0f);
    cube.orientation     = glm::angleAxis(glm::radians(20.0f), glm::vec3(0.0f, 0.0f, 1.0f));
    // ~20 degree tilt around Z, as if leaning to one side before release.
    cube.angularVelocity = glm::vec3(0.0f, 0.0f, 0.6f);
    // A small initial spin matching the tilt direction.
    setCubeMassProperties(cube, 1.0f);
    cube.restitution = 0.2f;
    cube.friction    = 0.6f;
    // Higher friction so the floor can actually damp the spin down via
    // friction torque, rather than the cube sliding/spinning freely.
    bodies.push_back(cube);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestHitCenter() {
    // Day 14 Test 3: Hit a cube near its center.
    // A moving cube strikes a stationary cube dead-on, both at the exact
    // same height and depth. Expected: mostly translation. Because the
    // contact point (the centroid of the AABB overlap on every axis) lands
    // exactly level with both bodies' centers, the lever arm r has no
    // component perpendicular to the impulse -- r x impulse = 0 -- so this
    // produces (almost) no spin.
    std::vector<RigidBody> bodies;
 
    RigidBody mover;
    mover.position = glm::vec3(-3.0f, 3.0f, 0.0f);
    mover.velocity = glm::vec3(4.0f, 0.0f, 0.0f);
    setCubeMassProperties(mover, 1.0f);
    mover.restitution = 0.4f;
    mover.friction    = 0.3f;
    bodies.push_back(mover);
 
    RigidBody target;
    target.position = glm::vec3(0.0f, 3.0f, 0.0f);
    // Exactly the same height and depth as 'mover' -- a true center hit.
    target.velocity = glm::vec3(0.0f);
    setCubeMassProperties(target, 1.0f);
    target.restitution = 0.4f;
    target.friction    = 0.3f;
    bodies.push_back(target);
 
    return bodies;
}
 
std::vector<RigidBody> spawnTestHitCorner() {
    // Day 14 Test 4: Hit a cube near one corner.
    // Same setup as spawnTestHitCenter(), but the moving cube is offset
    // vertically so the contact happens off-center. Expected: translation
    // PLUS noticeable rotation -- the offset lever arm r is no longer
    // parallel to the impulse, so r x impulse is nonzero and both cubes
    // pick up angular velocity from the hit.
    std::vector<RigidBody> bodies;
 
    RigidBody mover;
    mover.position = glm::vec3(-3.0f, 2.6f, 0.0f);
    // 0.4 units lower than the target -- overlaps only the lower portion
    // of the target's face on impact, producing an off-center contact point.
    mover.velocity = glm::vec3(4.0f, 0.0f, 0.0f);
    setCubeMassProperties(mover, 1.0f);
    mover.restitution = 0.4f;
    mover.friction    = 0.3f;
    bodies.push_back(mover);
 
    RigidBody target;
    target.position = glm::vec3(0.0f, 3.0f, 0.0f);
    target.velocity = glm::vec3(0.0f);
    setCubeMassProperties(target, 1.0f);
    target.restitution = 0.4f;
    target.friction    = 0.3f;
    bodies.push_back(target);
 
    return bodies;
}



int main() {
    if (!glfwInit()) {
        std::cerr << "Failed to initialize GLFW" << std::endl;
        return -1;
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    #ifdef __APPLE__
        glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
    #endif

    const GLFWvidmode* VideoMode = glfwGetVideoMode(glfwGetPrimaryMonitor());
    const auto ScreenHeight = VideoMode->height;
    GLFWwindow* window = glfwCreateWindow(ScreenHeight / 2, ScreenHeight / 2, "Hello Physics Engine!", NULL, NULL);

    if (window == NULL) {
        std::cerr << "Failed to create GLFW window" << std::endl;
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);

    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        std::cerr << "Failed to initialize GLAD" << std::endl;
        return -1;
    }

    glfwSetFramebufferSizeCallback(window, framebufferSizeChanged);
    glfwSetMouseButtonCallback(window, mouseButtonCallback);
    glfwSetCursorPosCallback(window, cursorPosCallback);
    glfwSetScrollCallback(window, scrollCallback);

    Render renderer;
    Cube cube(1.0f);
    // One shared cube mesh. Every body uses this same VAO, just drawn at a
    // different world position via a different model matrix each draw call.

    Camera camera(11.0f, -55.0f, 18.0f);
    activeCamera = &camera;
 
    PhysicsSolver physicsSolver;
 
    // -----------------------------------------------------------------
    // Uncomment exactly ONE line below to choose which test scenario runs.
    // -----------------------------------------------------------------
    // std::vector<RigidBody> bodies = spawnTestHeadOn();
    // std::vector<RigidBody> bodies = spawnTestVertical();
    // std::vector<RigidBody> bodies = spawnTestDiagonal();
    // std::vector<RigidBody> bodies = spawnTestDifferentMasses();
    // std::vector<RigidBody> bodies = spawnTestSlidingCube();
    // std::vector<RigidBody> bodies = spawnTestCubeOnCube();
    // std::vector<RigidBody> bodies = spawnTestCubeStack();
    std::vector<RigidBody> bodies = spawnTestPushStack();
    // std::vector<RigidBody> bodies = spawnTestFallingCubes();
    // std::vector<RigidBody> bodies = spawnTestFrictionComparison();
    // std::vector<RigidBody> bodies = spawnTestDropFlat();
    // std::vector<RigidBody> bodies = spawnTestDropTilted();
    // std::vector<RigidBody> bodies = spawnTestHitCenter();
    // std::vector<RigidBody> bodies = spawnTestHitCorner();

 
    // Fixed timestep 
    static constexpr float FIXED_DT = 1.0f / 60.0f;
    float accumulator = 0.0f;
    float lastTime = static_cast<float>(glfwGetTime());
    float lastDebugTime = static_cast<float>(glfwGetTime());
 
    while (!glfwWindowShouldClose(window)) {
 
        // Frame time 
        const float currentTime = static_cast<float>(glfwGetTime());
        float frameTime = currentTime - lastTime;
        frameTime = std::min(frameTime, 0.25f);
        lastTime = currentTime;
        accumulator += frameTime;
 
        // Physics loop 
        const float physicsStart = static_cast<float>(glfwGetTime());
 
        while (accumulator >= FIXED_DT) {
            for (auto& body : bodies) {
                physicsSolver.integrate(body, FIXED_DT);
                // Pass 1: gravity + Euler integration, per body.
            }

            // for (auto& body : bodies) {
            //     physicsSolver.floorCollision(body);
            //     // Pass 2: floor response per body (uses per-body restitution).
            // }

            physicsSolver.detectAndResolve(bodies);
            // Pass 2: pairwise detection + penetration correction + impulse iterations (all inside detectAndResolve).
            accumulator -= FIXED_DT;
        }
 
        const float physicsTimeMs = (static_cast<float>(glfwGetTime()) - physicsStart) * 1000.0f;
 
        // Debug statistics (printed once per 1/10th of a second)
        if (currentTime - lastDebugTime >= 0.1f) {
            const int pairCount = static_cast<int>(bodies.size() * (bodies.size() - 1) / 2);
            std::cout << "[Physics] " << "Bodies: " << bodies.size() << "  |  Pairs: "    << pairCount << "  |  Contacts: " << physicsSolver.lastContactCount << "  |  Time: "     << std::fixed << std::setprecision(2) << physicsTimeMs     << " ms\n";
            lastDebugTime = currentTime;
        }

        // Render all bodies into the same frame

        int width, height;
        glfwGetFramebufferSize(window, &width, &height);
        const float aspectRatio = height > 0 ? static_cast<float>(width) / static_cast<float>(height) : 1.0f;

        // Clears the color and depth buffers ONCE for this frame.
        // Must happen before any drawBody() calls; the clear resets the
        // depth buffer so all cubes depth-test against each other correctly.
        renderer.beginFrame();

        /** 
         * Draws this body at its current physics position with its collisiondebug color. 
         * Each call sets its own model matrix uniform, so the same cube mesh gets "stamped" at each body's position in turn.
         * The depth buffer accumulates all cubes: a face of body[7] can correctly occlude a face of body[3] that's behind it.
         */
        for (const auto& body : bodies) {
            renderer.drawBody(cube, camera, aspectRatio, body.position, body.orientation, body.isColliding);
        }

        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwTerminate();
    return 0;
}